### ISSUE TITLE
Bad false sharing example

### ISSUE THREAD

**Issue by foool** [MJjainam/falseSharing#2]
The main issue is accounting for the time it takes to create and destroy threads, which can skew the results. Specifically, the time it takes to create and destroy threads can be much greater than the time it takes to carry out operations in threads, which can affect the results. To verify this, you can switch the order of the false-share example and the non-false-share example and observe the differences in performance.

**Comment by MJjainam** [comment]
@foool We are creating the threads for both with false sharing and without false sharing. How is it that the results are skewed?

**Comment by foool** [comment]
You have included the time to create and destroy threads, which is much larger than your false-sharing/non-false-sharing testing time.

**Comment by MJjainam** [comment]
There are two threads created and destroyed. The loop runs for about 10^8 times. The time taken for creating thread will be much lesser than the thread creation and destruction time. 

Also, if what you say is right, the parallel computation without false sharing would take more time than serial computation where no threads are created. 

Please give more concrete evidence on the issue raised by you.
